libs.CopyLibs.classpath=\
    ${base}/CopyLibs/org-netbeans-modules-java-j2seproject-copylibstask.jar
libs.CopyLibs.displayName=CopyLibs Task
libs.CopyLibs.prop-version=3.0
libs.DizzyEngine.classpath=\
    ${base}/DizzyEngine/joml-1.10.9.jar:\
    ${base}/DizzyEngine/lwjgl-assimp.jar:\
    ${base}/DizzyEngine/lwjgl-glfw.jar:\
    ${base}/DizzyEngine/lwjgl-nfd.jar:\
    ${base}/DizzyEngine/lwjgl-openal.jar:\
    ${base}/DizzyEngine/lwjgl-opengl.jar:\
    ${base}/DizzyEngine/lwjgl-openvr.jar:\
    ${base}/DizzyEngine/lwjgl-stb.jar:\
    ${base}/DizzyEngine/lwjgl.jar:\
    ${base}/DizzyEngine/lwjglx-debug-1.0.0.jar:\
    ${base}/DizzyEngine/lwjgl-assimp-natives-linux-arm32.jar:\
    ${base}/DizzyEngine/lwjgl-assimp-natives-linux-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-assimp-natives-linux.jar:\
    ${base}/DizzyEngine/lwjgl-assimp-natives-macos-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-assimp-natives-macos.jar:\
    ${base}/DizzyEngine/lwjgl-assimp-natives-windows-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-assimp-natives-windows-x86.jar:\
    ${base}/DizzyEngine/lwjgl-assimp-natives-windows.jar:\
    ${base}/DizzyEngine/lwjgl-glfw-natives-linux-arm32.jar:\
    ${base}/DizzyEngine/lwjgl-glfw-natives-linux-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-glfw-natives-linux.jar:\
    ${base}/DizzyEngine/lwjgl-glfw-natives-macos-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-glfw-natives-macos.jar:\
    ${base}/DizzyEngine/lwjgl-glfw-natives-windows-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-glfw-natives-windows-x86.jar:\
    ${base}/DizzyEngine/lwjgl-glfw-natives-windows.jar:\
    ${base}/DizzyEngine/lwjgl-natives-linux-arm32.jar:\
    ${base}/DizzyEngine/lwjgl-natives-linux-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-natives-linux.jar:\
    ${base}/DizzyEngine/lwjgl-natives-macos-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-natives-macos.jar:\
    ${base}/DizzyEngine/lwjgl-natives-windows-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-natives-windows-x86.jar:\
    ${base}/DizzyEngine/lwjgl-natives-windows.jar:\
    ${base}/DizzyEngine/lwjgl-nfd-natives-linux-arm32.jar:\
    ${base}/DizzyEngine/lwjgl-nfd-natives-linux-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-nfd-natives-linux.jar:\
    ${base}/DizzyEngine/lwjgl-nfd-natives-macos-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-nfd-natives-macos.jar:\
    ${base}/DizzyEngine/lwjgl-nfd-natives-windows-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-nfd-natives-windows-x86.jar:\
    ${base}/DizzyEngine/lwjgl-nfd-natives-windows.jar:\
    ${base}/DizzyEngine/lwjgl-openal-natives-linux-arm32.jar:\
    ${base}/DizzyEngine/lwjgl-openal-natives-linux-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-openal-natives-linux.jar:\
    ${base}/DizzyEngine/lwjgl-openal-natives-macos-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-openal-natives-macos.jar:\
    ${base}/DizzyEngine/lwjgl-openal-natives-windows-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-openal-natives-windows-x86.jar:\
    ${base}/DizzyEngine/lwjgl-openal-natives-windows.jar:\
    ${base}/DizzyEngine/lwjgl-opengl-natives-linux-arm32.jar:\
    ${base}/DizzyEngine/lwjgl-opengl-natives-linux-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-opengl-natives-linux.jar:\
    ${base}/DizzyEngine/lwjgl-opengl-natives-macos-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-opengl-natives-macos.jar:\
    ${base}/DizzyEngine/lwjgl-opengl-natives-windows-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-opengl-natives-windows-x86.jar:\
    ${base}/DizzyEngine/lwjgl-opengl-natives-windows.jar:\
    ${base}/DizzyEngine/lwjgl-openvr-natives-linux-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-openvr-natives-linux.jar:\
    ${base}/DizzyEngine/lwjgl-openvr-natives-macos.jar:\
    ${base}/DizzyEngine/lwjgl-openvr-natives-windows-x86.jar:\
    ${base}/DizzyEngine/lwjgl-openvr-natives-windows.jar:\
    ${base}/DizzyEngine/lwjgl-stb-natives-linux-arm32.jar:\
    ${base}/DizzyEngine/lwjgl-stb-natives-linux-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-stb-natives-linux.jar:\
    ${base}/DizzyEngine/lwjgl-stb-natives-macos-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-stb-natives-macos.jar:\
    ${base}/DizzyEngine/lwjgl-stb-natives-windows-arm64.jar:\
    ${base}/DizzyEngine/lwjgl-stb-natives-windows-x86.jar:\
    ${base}/DizzyEngine/lwjgl-stb-natives-windows.jar:\
    ${base}/DizzyEngine/gson-2.14.0.jar
libs.DizzyEngine.javadoc=\
    ${base}/DizzyEngine/joml-1.10.9-javadoc.jar!//:\
    ${base}/DizzyEngine/lwjgl-assimp-javadoc.jar!//:\
    ${base}/DizzyEngine/lwjgl-glfw-javadoc.jar!//:\
    ${base}/DizzyEngine/lwjgl-javadoc.jar!//:\
    ${base}/DizzyEngine/lwjgl-nfd-javadoc.jar!//:\
    ${base}/DizzyEngine/lwjgl-openal-javadoc.jar!//:\
    ${base}/DizzyEngine/lwjgl-opengl-javadoc.jar!//:\
    ${base}/DizzyEngine/lwjgl-openvr-javadoc.jar!//:\
    ${base}/DizzyEngine/lwjgl-stb-javadoc.jar!//:\
    ${base}/DizzyEngine/lwjglx-debug-1.0.0-javadoc.jar!//
libs.DizzyEngine.src=\
    ${base}/DizzyEngine/joml-1.10.9-sources.jar!//:\
    ${base}/DizzyEngine/lwjgl-assimp-sources.jar:\
    ${base}/DizzyEngine/lwjgl-glfw-sources.jar!//:\
    ${base}/DizzyEngine/lwjgl-nfd-sources.jar!//:\
    ${base}/DizzyEngine/lwjgl-openal-sources.jar!//:\
    ${base}/DizzyEngine/lwjgl-opengl-sources.jar!//:\
    ${base}/DizzyEngine/lwjgl-openvr-sources.jar!//:\
    ${base}/DizzyEngine/lwjgl-sources.jar!//:\
    ${base}/DizzyEngine/lwjgl-stb-sources.jar:\
    ${base}/DizzyEngine/lwjglx-debug-1.0.0-sources.jar!//
