package net.ncplanner.plannerator.planner.ncpf.module;
public class UnderhaulSFRSettingsModule extends NCPFSettingsModule{
    public int minSize;
    public int maxSize;
    public int neutronReach;
    public float moderatorExtraPower;
    public float moderatorExtraHeat;
    public int activeCoolerRate;
    public UnderhaulSFRSettingsModule(){
        super("nuclearcraft:underhaul_sfr_configuration_settings");
        addInteger("min_size", ()->minSize, (v)->minSize = v, "Minimum Size", "The minimum size of this multiblock");
        addFloat("moderator_extra_power", ()->moderatorExtraPower, (v)->moderatorExtraPower = v, "Moderator Extra Power", "Determines the extra power generated by each moderator block adjacent to a reactor cell.\n Equal to the effective number of extra cell's worth of power that would be generated by a cell totally surrounded by moderator blocks.\n Each moderator block will contribute one sixth of this amount of power (the amount of additional power scales linearly with the number of moderator blocks)");
        addInteger("neutron_reach", ()->neutronReach, (v)->neutronReach = v, "Neutron Reach", "Maximum number of moderator blocks that can be between two cells for neutron radiation to be shared between them and their efficiency to increase");
        addInteger("max_size", ()->maxSize, (v)->maxSize = v, "Maximum Size", "The maximum size of this multiblock");
        addFloat("moderator_extra_heat", ()->moderatorExtraHeat, (v)->moderatorExtraHeat = v, "Moderator Extra Heat", "Determines the extra heat generated by each moderator block adjacent to a reactor cell.\n Equal to the effective number of extra cell's worth of heat that would be generated by a cell totally surrounded by moderator blocks.\n Each moderator block will contribute one sixth of this amount of heat (the amount of additional heat scales linearly with the number of moderator blocks)");
        addInteger("active_cooler_rate", ()->activeCoolerRate, (v)->activeCoolerRate = v, "Active Cooler Rate", "Maximum rate at which the Active Fluid Cooler uses coolant in mB/s");
    }
}